### ISSUE TITLE
The extension does not work sometime

### ISSUE THREAD

**Issue by Rick0317** [Rick0317/Eco-friendly#2]
# Network
For the network.js file, sometimes the extension does not show the data(KB)

# Image count
For the image.js file, only for a few websites, the extension shows the count of images. 
The js code in test_extension does the job and count the images though.

# Other properties
For other properties such as cookies, and profiler, things do not work either because of my code or the same issue as above

**Comment by Rick0317** [comment]
For a data website, the extension does not show the data (KB)
Because using the debugger, it somehow

**Comment by ktakeda02** [comment]
Click the blue cancel button below the search box, and run the extension again!
(I know it's not ideal but this is the only fix for now)
